apiVersion: v2
name: k8s-ssh
description: Deploy a DaemonSet that enables SSH access to Kubernetes node by injecting SSH public keys
type: application
version: 1.0.7
appVersion: "0.0.3"
maintainers:
  - name: xin
    email: xin@marxbiotech.com
